local QBCore = exports['qb-core']:GetCoreObject()

QBCore.Functions.CreateUseableItem('book_batterup', function(source, item)
    local Player = QBCore.Functions.GetPlayer(source)
    TriggerClientEvent('bostra-powerups:client:stamina', source)
    Player.Functions.RemoveItem('book_batterup', 1)
    TriggerClientEvent('inventory:client:ItemBox', source, QBCore.Shared.Items['book_batterup'], "remove", 1)
end)

QBCore.Functions.CreateUseableItem('book_brawler', function(source, item)
    local Player = QBCore.Functions.GetPlayer(source)
    TriggerClientEvent('bostra-powerups:client:strength', source)
    Player.Functions.RemoveItem('book_brawler', 1)
    TriggerClientEvent('inventory:client:ItemBox', source, QBCore.Shared.Items['book_brawler'], "remove", 1)
end)

QBCore.Functions.CreateUseableItem('book_clothing', function(source, item)
    local Player = QBCore.Functions.GetPlayer(source)
    TriggerClientEvent('bostra-powerups:client:crafting', source)
    Player.Functions.RemoveItem('book_clothing', 1)
    TriggerClientEvent('inventory:client:ItemBox', source, QBCore.Shared.Items['book_clothing'], "remove", 1)
end)

QBCore.Functions.CreateUseableItem('book_enforcer', function(source, item)
    local Player = QBCore.Functions.GetPlayer(source)
    TriggerClientEvent('bostra-powerups:client:hitman', source)
    Player.Functions.RemoveItem('book_enforcer', 1)
    TriggerClientEvent('inventory:client:ItemBox', source, QBCore.Shared.Items['book_enforcer'], "remove", 1)
end)

QBCore.Functions.CreateUseableItem('book_heist', function(source, item)
    local Player = QBCore.Functions.GetPlayer(source)
    TriggerClientEvent('bostra-powerups:client:criminal', source)
    Player.Functions.RemoveItem('book_heist', 1)
    TriggerClientEvent('inventory:client:ItemBox', source, QBCore.Shared.Items['book_heist'], "remove", 1)
end)

QBCore.Functions.CreateUseableItem('book_hunting', function(source, item)
    local Player = QBCore.Functions.GetPlayer(source)
    TriggerClientEvent('bostra-powerups:client:hunting', source)
    Player.Functions.RemoveItem('book_hunting', 1)
    TriggerClientEvent('inventory:client:ItemBox', source, QBCore.Shared.Items['book_hunting'], "remove", 1)
end)

QBCore.Functions.CreateUseableItem('book_looter', function(source, item)
    local Player = QBCore.Functions.GetPlayer(source)
    TriggerClientEvent('bostra-powerups:client:searching', source)
    Player.Functions.RemoveItem('book_looter', 1)
    TriggerClientEvent('inventory:client:ItemBox', source, QBCore.Shared.Items['book_looter'], "remove", 1)
end)

QBCore.Functions.CreateUseableItem('book_mining', function(source, item)
    local Player = QBCore.Functions.GetPlayer(source)
    TriggerClientEvent('bostra-powerups:client:mining', source)
    Player.Functions.RemoveItem('book_mining', 1)
    TriggerClientEvent('inventory:client:ItemBox', source, QBCore.Shared.Items['book_mining'], "remove", 1)
end)

QBCore.Functions.CreateUseableItem('book_techjunkie', function(source, item)
    local Player = QBCore.Functions.GetPlayer(source)
    TriggerClientEvent('bostra-powerups:client:hacking', source)
    Player.Functions.RemoveItem('book_techjunkie', 1)
    TriggerClientEvent('inventory:client:ItemBox', source, QBCore.Shared.Items['book_techjunkie'], "remove", 1)
end)

QBCore.Functions.CreateUseableItem('book_treasurehunt', function(source, item)
    local Player = QBCore.Functions.GetPlayer(source)
    TriggerClientEvent('bostra-powerups:client:searching', source)
    Player.Functions.RemoveItem('book_treasurehunt', 1)
    TriggerClientEvent('inventory:client:ItemBox', source, QBCore.Shared.Items['book_treasurehunt'], "remove", 1)
end)
